module.exports = {
    'extends': [
        'stylelint-config-recommended-scss',
    ],
    'plugins': [
        'stylelint-order',
        'stylelint-declaration-block-no-ignored-properties',
        'stylelint-color-format',
        'stylelint-high-performance-animation',
        'stylelint-csstree-validator',
        'stylelint-no-unresolved-module',
        '@signal-noise/stylelint-scales',
        'stylelint-no-unsupported-browser-features',
    ],
    'rules': {
        'plugin/no-unsupported-browser-features': [true, {
            'severity': 'warning',
            ignore: [],
        }],
        'csstree/validator': {
            'syntaxExtensions': ['sass'],
            'ignoreProperties': [],
        },
        'plugin/no-unresolved-module': {},
        'plugin/declaration-block-no-ignored-properties': true,
        'plugin/no-low-performance-animation-properties': true,
        'block-opening-brace-space-before': 'always',
        'declaration-block-semicolon-space-before': 'never',
        'at-rule-semicolon-space-before': 'never',
        'declaration-block-no-redundant-longhand-properties': true,
        'number-leading-zero': 'always',
        'length-zero-no-unit': true,
        'color-named': 'never',
        'color-format/format': {'format': 'rgb'},
        'declaration-bang-space-before': 'always',
        'declaration-bang-space-after': 'never',
        'declaration-colon-space-after': 'always',
        'declaration-colon-space-before': 'never',
        'custom-property-empty-line-before': 'never',
        'declaration-empty-line-before': [
            'always',
            {
                'except': [
                    'after-declaration',
                    'first-nested',
                ],
            },
        ],
        'declaration-property-value-disallowed-list': {
            '/^transition/': ['/all/'],
            '/^background/': ['http:', 'https:'],
            '/^border/': ['none'],
            '/^display/': [],
            '/.+/': ['initial'],
        },
        'color-function-notation': 'legacy',
        'alpha-value-notation': 'number',
        'function-calc-no-unspaced-operator': true,
        'no-extra-semicolons': true,
        'max-nesting-depth': 10,
        'declaration-block-no-duplicate-properties': true,
        'string-quotes': 'single',
        'at-rule-no-vendor-prefix': true,
        'media-feature-name-no-vendor-prefix': true,
        'property-no-vendor-prefix': true,
        'value-no-vendor-prefix': true,
        'selector-no-vendor-prefix': true,
        'max-empty-lines': 2,
        'no-missing-end-of-source-newline': true,
        'no-eol-whitespace': true,
        'no-empty-source': true,
        'selector-combinator-space-before': 'always',
        'selector-combinator-space-after': 'always',
        'scss/dollar-variable-no-missing-interpolation': true,
        'function-comma-space-before': 'never',
        'function-comma-space-after': 'always',
        'scss/dollar-variable-colon-space-after': 'always',
        'scss/dollar-variable-colon-space-before': 'never',
        'scss/no-duplicate-dollar-variables': true,
        'scss/operator-no-newline-before': true,
        'scss/operator-no-newline-after': true,
        'scss/operator-no-unspaced': true,
        'scss/at-import-partial-extension': null,
        'scss/dollar-variable-empty-line-after': [
            'always',
            {
                'except': ['last-nested', 'before-dollar-variable'],
            },
        ],
        'no-descending-specificity': null,
        'selector-pseudo-class-no-unknown': [
            true,
            {'ignorePseudoClasses': ['global']},
        ],
        'at-rule-no-unknown': [
            true,
            {
                'ignoreAtRules': [
                    'at-root',
                    'content',
                    'debug',
                    'each',
                    'else',
                    'else if',
                    'error',
                    'extend',
                    'for',
                    'function',
                    'if',
                    'import',
                    'include',
                    'media',
                    'mixin',
                    'return',
                    'use',
                    'warn',
                    'while',
                    'import-normalize',
                ],
            },
        ],
        'selector-type-no-unknown': [
            true,
            {
                'ignore': [
                    'custom-elements',
                    'default-namespace',
                ],
            },
        ],
        'rule-empty-line-before': [
            'always',
            {
                'except': [
                    'after-rule',
                    'first-nested',
                    'after-single-line-comment',
                ],
            },
        ],
        'indentation': [4],
        'font-family-no-missing-generic-family-keyword': null,
        'color-hex-case': 'upper',
        'order/order': [
            [
                'dollar-variables',
                'custom-properties',
                {
                    'type': 'at-rule',
                    'name': 'extend',
                },
                {
                    'type': 'at-rule',
                    'name': 'include',
                    'hasBlock': false,
                },
                'declarations',
                {
                    'type': 'at-rule',
                    'name': 'include',
                    'hasBlock': true,
                },
                'rules',
                'at-rules',
            ],
        ],
        'order/properties-order': [
            'position',
            'top',
            'right',
            'bottom',
            'left',
            'z-index',
            'display',
            'align-content',
            'align-items',
            'align-self',
            'flex',
            'flex-basis',
            'flex-direction',
            'flex-flow',
            'flex-grow',
            'flex-shrink',
            'flex-wrap',
            'grid',
            'grid-area',
            'grid-auto-columns',
            'grid-auto-flow',
            'grid-auto-rows',
            'grid-column',
            'grid-column-end',
            'grid-column-gap',
            'grid-column-start',
            'grid-gap',
            'grid-row',
            'grid-row-end',
            'grid-row-gap',
            'grid-row-start',
            'grid-template',
            'grid-template-areas',
            'grid-template-columns',
            'grid-template-rows',
            'gap',
            'justify-content',
            'order',
            'float',
            'width',
            'height',
            'max-width',
            'max-height',
            'min-width',
            'min-height',
            'padding',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
            'margin',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'margin-collapse',
            'margin-top-collapse',
            'margin-right-collapse',
            'margin-bottom-collapse',
            'margin-left-collapse',
            'overflow',
            'overflow-x',
            'overflow-y',
            'clip',
            'clear',
            'font',
            'font-weight',
            'font-size',
            'font-family',
            'font-style',
            'font-variant',
            'font-size-adjust',
            'font-stretch',
            'font-effect',
            'font-emphasize',
            'font-emphasize-position',
            'font-emphasize-style',
            'font-smooth',
            'line-height',
            'hyphens',
            'letter-spacing',
            'word-spacing',
            'src',
            'color',
            'text-align',
            'text-decoration',
            'text-indent',
            'text-overflow',
            'text-rendering',
            'text-size-adjust',
            'text-shadow',
            'text-transform',
            'word-break',
            'word-wrap',
            'white-space',
            'vertical-align',
            'list-style',
            'list-style-type',
            'list-style-position',
            'list-style-image',
            'pointer-events',
            'cursor',
            'background',
            'background-attachment',
            'background-clip',
            'background-color',
            'background-image',
            'background-position',
            'background-repeat',
            'background-size',
            'border',
            'border-collapse',
            'border-top',
            'border-right',
            'border-bottom',
            'border-left',
            'border-color',
            'border-image',
            'border-top-color',
            'border-right-color',
            'border-bottom-color',
            'border-left-color',
            'border-spacing',
            'border-style',
            'border-top-style',
            'border-right-style',
            'border-bottom-style',
            'border-left-style',
            'border-width',
            'border-top-width',
            'border-right-width',
            'border-bottom-width',
            'border-left-width',
            'border-radius',
            'border-top-right-radius',
            'border-bottom-right-radius',
            'border-bottom-left-radius',
            'border-top-left-radius',
            'border-radius-topright',
            'border-radius-bottomright',
            'border-radius-bottomleft',
            'border-radius-topleft',
            'content',
            'quotes',
            'outline',
            'outline-offset',
            'outline-width',
            'outline-style',
            'outline-color',
            'opacity',
            'filter',
            'visibility',
            'size',
            'zoom',
            'transform',
            'box-align',
            'box-flex',
            'box-orient',
            'box-pack',
            'box-shadow',
            'box-sizing',
            'table-layout',
            'animation',
            'animation-delay',
            'animation-duration',
            'animation-iteration-count',
            'animation-name',
            'animation-play-state',
            'animation-timing-function',
            'animation-fill-mode',
            'transition',
            'transition-delay',
            'transition-duration',
            'transition-property',
            'transition-timing-function',
            'backface-visibility',
            'resize',
            'appearance',
            'user-select',
            'interpolation-mode',
            'direction',
            'marks',
            'page',
            'set-link-source',
            'unicode-bidi',
            'speak',
        ],
    },
};
