name: publish-on-firefox-add-ons
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Release tag to be published
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: robinraju/release-downloader@v1.8
        id: download
        with: 
          tag: ${{ github.event.inputs.tag }}
          fileName: yt-better-subscriptions-*.zip
          tarBall: false
          zipBall: false
          extract: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Firefox Addons
        id: addonsDeploy
        uses: cardinalby/webext-buildtools-firefox-addons-action@v1
        continue-on-error: true
        with:
          zipFilePath: ${{ fromJson(steps.download.outputs.downloaded_files)[0] }}
          extensionId: ${{ secrets.FF_EXTENSION_ID }}
          jwtIssuer: ${{ secrets.FF_JWT_ISSUER }}
          jwtSecret: ${{ secrets.FF_JWT_SECRET }}

      - name: Abort on upload error
        if: |
          steps.addonsDeploy.outcome == 'failure' &&
          steps.addonsDeploy.outputs.sameVersionAlreadyUploadedError != 'true' &&
          steps.addonsDeploy.outputs.timeoutError != 'true'
        run: exit 1
