name: Touch google token
on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetchToken:
    runs-on: ubuntu-latest
    steps:
      - uses: cardinalby/google-api-fetch-token-action@v1
        with:
          clientId: ${{ secrets.G_CLIENT_ID }}
          clientSecret: ${{ secrets.G_CLIENT_SECRET }}
          refreshToken: ${{ secrets.G_REFRESH_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@v1